[package]
name = "repose-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Platform runners (winit Desktop, Android and Web)"

[features]
desktop = ["winit", "repose-render-wgpu"]
android = ["winit/android-native-activity", "repose-render-wgpu"]
web = ["repose-render-wgpu"]

[dependencies]
repose-core.workspace = true
repose-ui.workspace = true
repose-navigation.workspace = true
repose-render-wgpu = { workspace = true, optional = true }
repose-devtools.workspace = true
winit = { workspace = true, optional = true }
log = { workspace = true }
anyhow = { workspace = true }
clipawl = { workspace = true, features = ["linux-wayland", "linux-x11"] }
web-time.workspace = true
pollster = "0.4.0"                                                        # trying to avoid tokio but might have to add later...
accesskit = "0.22"
accesskit_winit = "0.30"                                                  # Compatible with winit 0.30
rustc-hash = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "CssStyleDeclaration",
    "DragEvent",
    "DataTransfer",
    "FileList",
    "File",
] }
winit = { workspace = true, features = ["rwh_05"] }
console_error_panic_hook = "0.1"
console_log = "1.0"
log.workspace = true
getrandom = { version = "0.3.4", features = ["wasm_js"] }
wgpu.workspace = true
