[package]
name = "repose-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Platform runners (winit Desktop, Android and Web)"

[dependencies]
repose-app.workspace = true
repose-core = { workspace = true, features = ["accesskit"] }
repose-ui.workspace = true
repose-navigation.workspace = true
repose-render-wgpu.workspace = true
repose-devtools.workspace = true
log = { workspace = true }
anyhow = { workspace = true }
clipawl = { workspace = true, features = ["async-io", "linux-wayland", "linux-x11"] }
web-time.workspace = true
pollster = { workspace = true }
accesskit = { workspace = true }
rustc-hash = { workspace = true }

[target.'cfg(all(not(target_os = "android"), not(target_arch = "wasm32")))'.dependencies]
winit = { workspace = true }
accesskit_winit = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
winit = { workspace = true, features = ["android-native-activity"] }
accesskit_winit = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
repose-text = { workspace = true }
winit = { workspace = true, features = ["rwh_05"] }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
log.workspace = true
getrandom = { workspace = true, features = ["wasm_js"] }
wgpu.workspace = true
