[package]
name = "repose-material"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Material components for Repose"
[dependencies]
repose-core.workspace = true
repose-ui.workspace = true
repose-canvas.workspace = true
repose-text.workspace = true
repose-tree.workspace = true
web-time.workspace = true
