[package]
name = "repose-render-wgpu"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Repose wgpu handler"

[features]
default = ["winit-surface"]
winit-surface = ["dep:winit"]

[dependencies]
repose-core.workspace = true
repose-text.workspace = true
wgpu = { workspace = true }
winit = { workspace = true, optional = true }
log = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
] }
lyon_tessellation = "1.0"
lyon_path = "1.0"
