[package]
name = "repose-render-wgpu"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Repose wgpu handler"

[features]
default = ["winit-surface", "fragile-send-sync-non-atomic-wasm"]
winit-surface = ["dep:winit"]

# Disable if targeting wasm with atomics/threads (web-workers).
fragile-send-sync-non-atomic-wasm = ["wgpu/fragile-send-sync-non-atomic-wasm"]

[dependencies]
repose-core.workspace = true
repose-text.workspace = true
wgpu = { workspace = true }
winit = { workspace = true, optional = true }
log = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
web-workers.workspace = true
image = { workspace = true }
lyon_tessellation = { workspace = true }
lyon_path = { workspace = true }
