[package]
name = "repose-canvas"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Immediate-mode canvas utilities for Repose"
[dependencies]
repose-core.workspace = true
repose-ui.workspace = true
lyon_tessellation.workspace = true
lyon_path.workspace = true
