[workspace]
members = [
  "crates/repose-core",
  "crates/repose-tree",
  "crates/repose-ui",
  "crates/repose-render-wgpu",
  "crates/repose-platform",
  "crates/repose-devtools",
  "crates/repose-macros",
  "crates/repose-text",
  "crates/repose-canvas",
  "crates/repose-material",
  "crates/repose-navigation",
  "examples/showcase",
  "examples/animation_demo",
  "examples/android_counter",
  "crates/repose-docking",
]
resolver = "2"

[workspace.package]
version = "0.17.0"
edition = "2024"
license = "LGPL-2.1-or-later"
repository = "https://github.com/mlm-games/repose"
rust-version = "1.93"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
log = "0.4"
env_logger = "0.11"
parking_lot = "0.12"
smallvec = "1.15"
slotmap = "1.1"
bitflags = "2.11.1"
unicode-segmentation = "1.13"
clipawl = { version = "0.2.1" }

# Common
serde_json = "1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
  "Document",
  "Window",
  "Element",
  "HtmlElement",
  "HtmlCanvasElement",
  "CssStyleDeclaration",
] }
console_error_panic_hook = "0.1"
console_log = "1"
getrandom = "0.3"
bytemuck = { version = "1.25.0", features = ["derive"] }

# Layout
taffy = { version = "0.10", default-features = true }

# Platform + GPU
winit = { version = "0.30", default-features = true }
wgpu = "29"
pollster = "0.4.0"

# Text
ab_glyph = "0.2.32"
fontdb = "0.23.0"
cosmic-text = { version = "0.19", default-features = true, features = [
  "swash",
] }

android_logger = "0.15"
serde = { version = "1", features = ["derive"] }
web-time = "1"
rustc-hash = "2.1"
ahash = "0.8"

repose-core = { path = "crates/repose-core", version = "0.17.0" }
repose-ui = { path = "crates/repose-ui", version = "0.17.0" }
repose-material = { path = "crates/repose-material", version = "0.17.0" }
repose-canvas = { path = "crates/repose-canvas", version = "0.17.0" }
repose-navigation = { path = "crates/repose-navigation", version = "0.17.0" }
repose-devtools = { path = "crates/repose-devtools", version = "0.17.0" }
repose-text = { path = "crates/repose-text", version = "0.17.0" }
repose-render-wgpu = { path = "crates/repose-render-wgpu", version = "0.17.0" }
repose-platform = { path = "crates/repose-platform", version = "0.17.0" }
repose-tree = { path = "crates/repose-tree", version = "0.17.0" }
repose-docking = { path = "crates/repose-docking", version = "0.17.0" }
repose-macros = { path = "crates/repose-macros", version = "0.17.0" }
