[package]
name = "repose-navigation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Navigation (Nav3-like) for Repose"

[dependencies]
repose-core.workspace = true
repose-ui.workspace = true
log.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
