[package]
name = "repose-navigation"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Navigation (Nav3-like) for Repose"

[dependencies]
repose-core.workspace = true
repose-ui.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
log.workspace = true
