[package]
name = "repose-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "UI widgets and libs for Repose"

[dependencies]
repose-core.workspace = true
repose-text.workspace = true
repose-tree.workspace = true
taffy = { workspace = true }
unicode-segmentation = { workspace = true }
log.workspace = true
web-time.workspace = true
rustc-hash = { workspace = true }
webbrowser = { workspace = true }
