name: Deploy Showcase to GH Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    uses: mlm-games/ci/.github/workflows/pages.yml@main
    with:
      working-directory: examples/showcase
      dist-dir: examples/showcase/dist