name: Deploy Showcase to GH Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: mlm-games/ci/.github/workflows/pages.yml@main
    with:
      working-directory: examples/showcase
      dist-dir: dist